import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const Intro = localFont({
  src: "../assets/4488-font.otf",
});

export const metadata: Metadata = {
  title: "PROJECT:Charlie",
  description: "Generated by create next app",
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Intro.className}>{children}</body>
    </html>
  );
}
